### ISSUE TITLE
feature: support caching of signature databases

### ISSUE THREAD

**Issue by sebthom** [toblux/start-clamd-github-action#3]
It would be great if GHA caching could be provided for bytecode.cvd, main.cvd and on windows for the exe installer file. This reduces installation time, load on external systems and gives some level of protection from external systems being offline.

At least on Linux it seems you can manually install the CVD files (i.e. load them from the cache) https://askubuntu.com/questions/1046700/how-do-i-manually-import-the-clamav-virus-definition-file

**Comment by Pamplemousse** [comment]
I believe that this can be achieved using the [`actions/cache` GHA](https://github.com/actions/cache):

```yaml
- name: Cache `clamd` databases
  id: cache-CVDs
  uses: actions/cache@v6
  with:
    path: |
      /var/lib/clamav/*/bytecode.cvd
      /var/lib/clamav/*/main.cvd
    key: ${{ runner.os }}-CVDs

# ...
```
