### ISSUE TITLE
BUG - db_main and db_daily inputs are not passed.

### ISSUE THREAD

**Issue by RLI-Rdeaton** [toblux/start-clamd-github-action#4]
Issue:

Consider the following Action-

```
      -
        name: Start ClamAV daemon
        uses: toblux/start-clamd-github-action@v0.1
        with:
          db_main: true
          db_daily: true
```

Per the action.yml file, this should work.

However, I get the following warning-

```
Warning: Unexpected input(s) 'db_main', 'db_daily', valid inputs are ['unix_socket', 'tcp_port', 'stream_max_length', 'log_verbose', 'log_file', 'debug']
```

And the parameters are not passed.  Playing around with log_file and log_verbose those seem to be passed.  I can probably just make it do what I want it to do after running the action as a bootstrap, but that's probably not ideal.  I figured I'd bring this up since you have it on the marketplace.
